<?php


namespace App\Domains\Products\Managers;


use App\Domains\Products\Repositories\CategoryRepository;
use App\Domains\Products\Repositories\ProductRepository;
use Freelabois\LaravelQuickstart\Extendables\ManipulationManager;

class ProductManager extends ManipulationManager
{
    /**
     * @var CategoryRepository
     */
    private $category_repository;

    public function __construct(
        ProductRepository $repository,
        CategoryRepository $category_repository
    )
    {
        parent::__construct($repository);
        $this->category_repository = $category_repository;
    }

    public function storeOrUpdate($values, int $id = null, array $relations = [])
    {
        if ($values['category']) {
            $relations[] = [
                'model' => $this->category_repository->find($values['category']),
                'name' => 'category'
            ];
        }

        return parent::storeOrUpdate($values, $id, $relations); // TODO: Change the autogenerated stub
    }


}
